name: VillagerNames
main: mn.frd.VillagerNames.VillagerNames
version: 0.1b
website: http://frd.mn
author: frdmn
description: >
            Plugin to name villagers as soon as they spawn based on a dictionary
            Custom version that includes a zombie feature for Zerkhaan.